BAU: General improvements to staging run
- Group related tasks together
- Removed redundant environment variables
- Reduced parallelisation overheads by separating out containers
- Consolidated report handling

diff --git a/.github/workflows/regressionStaging.yml b/.github/workflows/regressionStaging.yml
--- a/.github/workflows/regressionStaging.yml
+++ b/.github/workflows/regressionStaging.yml
@@ -30,6 +30,7 @@ jobs:
       output1: ${{ steps.cypress-outcome.outputs.test-status-1 }}
       output2: ${{ steps.cypress-outcome.outputs.test-status-2 }}
       output3: ${{ steps.cypress-outcome.outputs.test-status-3 }}
+
     steps:
       - run: date
 
@@ -51,7 +52,7 @@ jobs:
           spec: ${{ steps.speclist.outputs.specfiles }}
           quiet: true
           browser: chrome
-      
+
       - name: Cypress test outcome
         id: cypress-outcome
         run: |
@@ -69,7 +70,8 @@ jobs:
     if: always()
     runs-on: ubuntu-22.04
     outputs:
-      date-output: ${{ steps.date.outputs.date}}
+      date-output: ${{ steps.date.outputs.date }}
+
     steps:
       - name: Install dependencies
         run: npm install --save-dev mochawesome mochawesome-merge mochawesome-report-generator
@@ -77,45 +79,47 @@ jobs:
       - name: Create reports directory
         run: mkdir reports
 
-      - name: Download test-reports-0
+      - name: Checkout reports repo
+        uses: actions/checkout@v2
+        with:
+          ref: reports
+          path: reports_repo
+
+      - name: Download artifacts
         uses: actions/download-artifact@v3
         with:
           name: test-reports-0
           path: reports/0
-
-      - name: Download test-reports-1
+      - name: Download artifacts
         uses: actions/download-artifact@v3
         with:
           name: test-reports-1
           path: reports/1
-
-      - name: Download test-reports-2
+      - name: Download artifacts
         uses: actions/download-artifact@v3
         with:
           name: test-reports-2
           path: reports/2
-
-      - name: Download test-reports-3
+      - name: Download artifacts
         uses: actions/download-artifact@v3
         with:
           name: test-reports-3
           path: reports/3
 
-      - name: Move all reports into one directory
+      - name: Move reports to mochawesome-report directory
         run: |
           mkdir -p mochawesome-report
-          i=0
-          for file in $(find reports -type f -name mochawesome\*.json); do
-            filename=$(basename "$file" .json)-"$i".json
-            mv "$file" mochawesome-report/"$filename"
-            ls mochawesome-report
-            i=$((i + 1))
+          for container in {0..3}; do
+            download_path=reports/$container
+            for file in $(find $download_path -type f -name 'mochawesome*.json'); do
+              mv "$file" mochawesome-report/$(basename "$file" .json)-"$container".json
+            done
           done
 
       - name: Merge and generate reports
         run: |
           mkdir report
-          npx mochawesome-merge > report/index.json
+          npx mochawesome-merge mochawesome-report/*.json > report/index.json
           npx marge --inline report/index.json -o report/
 
       - name: Upload report
@@ -123,12 +127,6 @@ jobs:
         with:
           name: E2E Test Reports
           path: report/
-
-      - name: Checkout reports repo
-        uses: actions/checkout@v3
-        with:
-          ref: reports
-          path: reports_repo
 
       - name: Copy report into reports repo
         run: |
@@ -149,7 +147,7 @@ jobs:
           git config --local user.email "tradetarrif+github-actions[bot]@users.noreply.github.com"
           git config --local user.name "github-actions[bot]"
           git commit -m "Staging report for $(date +%d-%m-%Y)" -a
-      
+
       - name: Push changes
         uses: ad-m/github-push-action@master
         with:
@@ -159,54 +157,32 @@ jobs:
 
       - name: Get current date
         id: date
-        run: echo "::set-output name=date::$(date +'%d-%m-%Y')"
+        run: echo "date=$(date +'%d-%m-%Y')" >> $GITHUB_OUTPUT
 
-  build-status-pass:
-    name: Set build status and send slack notification when build is passed
+  notify-slack:
+    name: Send slack notification based on test results
     needs: [cypress-run, gen-report]
     if: always()
     runs-on: ubuntu-22.04
+
     steps:
-      - name: Set build status as output to pass it to slack when build is passed
-        id: final-test
-        if: needs.cypress-run.outputs.output0 == 'success' && needs.cypress-run.outputs.output1 == 'success' && needs.cypress-run.outputs.output2 == 'success' && needs.cypress-run.outputs.output3 == 'success'
-        run: echo "result=success" >> $GITHUB_OUTPUT
-      
+      - name: Determine test outcome
+        id: determine-outcome
+        run: |
+          if [[ "${{ needs.cypress-run.outputs.output0 }}" == "success" && "${{ needs.cypress-run.outputs.output1 }}" == "success" && "${{ needs.cypress-run.outputs.output2 }}" == "success" && "${{ needs.cypress-run.outputs.output3 }}" == "success" ]]; then
+            echo "result=success" >> $GITHUB_OUTPUT
+          else
+            echo "result=failure" >> $GITHUB_OUTPUT
+            exit 1
+          fi
+
       - name: Slack Notification
-        if: needs.cypress-run.outputs.output0 == 'success' && needs.cypress-run.outputs.output1 == 'success' && needs.cypress-run.outputs.output2 == 'success' && needs.cypress-run.outputs.output3 == 'success'
         uses: rtCamp/action-slack-notify@v2
         env:
           SLACK_CHANNEL: "tariffs-regression"
           SLACK_USERNAME: "Staging Regression"
           SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
           SLACK_ICON_EMOJI: ":alphabet-yellow-s:"
-          SLACK_COLOR: ${{ steps.final-test.outputs.result }}
-          SLACK_TITLE: Cypress finished with - ${{ steps.final-test.outputs.result }}
+          SLACK_COLOR: ${{ steps.determine-outcome.outputs.result }}
+          SLACK_TITLE: Cypress finished with - ${{ steps.determine-outcome.outputs.result }}
           SLACK_MESSAGE: https://trade-tariff.github.io/trade-tariff-testing/staging/${{ needs.gen-report.outputs.date-output }}/
-
-  build-status-fail:
-    name: Set build status and send slack notification when build is failed
-    needs: [cypress-run, gen-report]
-    if: always()
-    runs-on: ubuntu-22.04
-    steps:
-      - name: Set build status as output to pass it to slack when build is failed
-        id: final-test
-        if: needs.cypress-run.outputs.output0 != 'success' || needs.cypress-run.outputs.output1 != 'success' || needs.cypress-run.outputs.output2 != 'success' || needs.cypress-run.outputs.output3 != 'success'
-        run: echo "result=failure" >> $GITHUB_OUTPUT
-     
-      - name: Slack Notification
-        if: needs.cypress-run.outputs.output0 != 'success' || needs.cypress-run.outputs.output1 != 'success' || needs.cypress-run.outputs.output2 != 'success' || needs.cypress-run.outputs.output3 != 'success'
-        uses: rtCamp/action-slack-notify@v2
-        env:
-          SLACK_CHANNEL: "tariffs-regression"
-          SLACK_USERNAME: "Staging Regression"
-          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
-          SLACK_ICON_EMOJI: ":alphabet-yellow-s:"
-          SLACK_COLOR: ${{ steps.final-test.outputs.result }}
-          SLACK_TITLE: Cypress finished with - ${{ steps.final-test.outputs.result }}
-          SLACK_MESSAGE: https://trade-tariff.github.io/trade-tariff-testing/staging/${{ needs.gen-report.outputs.date-output }}/
-
-      - name: Set build status based on Cypress outcome
-        if: needs.cypress-run.outputs.output0 != 'success' || needs.cypress-run.outputs.output1 != 'success' || needs.cypress-run.outputs.output2 != 'success' || needs.cypress-run.outputs.output3 != 'success'
-        run: exit 1
